### ISSUE TITLE
Feature Proposal - wrap foreign buffers with the same XS magic

### ISSUE THREAD

**Issue by nrdvana** [Leont/file-map#10]
I have other XS code where I would like to take buffers which are not under perl's control and expose them to perl-space in a safe manner.  I looked at the internals of File::Map, and determined I'd need to copy about 90% of the code to get that effect.  Instead of that, would you be interested in having a new API added to this module which wraps some other buffer with the same magic, but calls some other callback upon the final release of the buffer rather than calling unmap?

**Comment by Leont** [comment]
Given the lack of infrastructure, I think this would be very hard to do. I fear your best option is to copy-paste the relevant code (I've had to do that before in SysV::SharedMem)
