### ISSUE TITLE
Question about values found in map

### ISSUE THREAD

**Issue by srynobio** [Leont/file-map#5]
I'm wondering if there is an ability to return the region found within a mapped variable similar to how perl uses $1, $2 to store found values.

```
map_file my $map, $file, '+<';

# 153993799 is a column in a file.
if ( $map =~ /153993799/ ) {
    return from $map just the region matched, not the entire file.
    ... 
}
```

--Thanks!

**Comment by Leont** [comment]
I'm not sure I understand your issue, why wouldn't regular expressions or `substr` work for your purpose?

**Comment by srynobio** [comment]
When I started working on capturing the region via a regular expression it did the trick:

```
#!/usr/bin/env perl
use strict;
use warnings;
use feature 'say';
use autodie;
use File::Map ':map';

my $file = $ARGV[0];

map_file my $map, $file, '<';

my $chr      = '1';
my $position = '70317';
my $ref      = 'G';

if ( $map =~ /(($chr)\s+($position)(.*)($ref)(.*)\n)/ ) {
    my $result = $1;
    say $result;
}
else {
    say "nothing";
}
```

However I saw another strange situation in regards to file size.  When the line I was looking for was within a > 40G file the above script printed "nothing", but when I subsetted the file to around ~5G my region was found.

**Question**: In your experience how do you determine the largest file size to use which will allow correct matching?

Again thanks for your work and help.

**Comment by Leont** [comment]
What version of perl are you using? Older versions of perl couldn't handle strings larger than 4GiB well, you really want to use perl 5.12 or higher if you want to do something like that on such files (this is actually documented under 'dependencies').

**Comment by srynobio** [comment]
After reviewing the 'dependencies' I understand the issue.  Thanks for clarifying this for me!
