### ISSUE TITLE
(question) Checking if variable mapped

### ISSUE THREAD

**Issue by eldhenn** [Leont/file-map#8]
How can I check if some scalar mapped to any BLOB using File::Map?

**Comment by Leont** [comment]
You can't. Why would you want that? What are you trying to achieve?

**Comment by eldhenn** [comment]
I have a 'File' structure, with one element mapped to blob and others represents metadata. And I want filter out blob (see all metadata) but not rely on element name.

**Comment by Leont** [comment]
This isn't making sense to me. Can you try again to explain it to me?
